name: "Aliyun Serverless Action"
description: "GitHub Actions for Aliyun Serverless 🚀 Deploy function automatically."
author: "Yunkun Huang"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.functionFolder }}
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  functionFolder:
    description: "Folder name for function"
    required: false
    default: "."
