name: ci

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/action:latest
        run: |
          docker build . --file Dockerfile-source --tag ${DOCKER_IMAGE}
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        run: shellcheck ./entrypoint.sh

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: burdzwastaken/hadolint-action@1.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
